// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDydaFPrCTP1L-LDGCa9_gU9P65aPREd5M',
    appId: '1:378941456442:web:b587f22e3bbdfc887e7503',
    messagingSenderId: '378941456442',
    projectId: 'edspert19',
    authDomain: 'edspert19.firebaseapp.com',
    storageBucket: 'edspert19.appspot.com',
    measurementId: 'G-1N9H7QVSBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFWlNOvCpzam3GACFHUbuq-2h9yydgpEI',
    appId: '1:378941456442:android:6ce51b0a338243b07e7503',
    messagingSenderId: '378941456442',
    projectId: 'edspert19',
    storageBucket: 'edspert19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI_vBdLil4cWz-9MpMyzGYIZGBSim2Wso',
    appId: '1:378941456442:ios:558af050ff0349207e7503',
    messagingSenderId: '378941456442',
    projectId: 'edspert19',
    storageBucket: 'edspert19.appspot.com',
    iosBundleId: 'com.example.edproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI_vBdLil4cWz-9MpMyzGYIZGBSim2Wso',
    appId: '1:378941456442:ios:ef3768dd8f48fa1a7e7503',
    messagingSenderId: '378941456442',
    projectId: 'edspert19',
    storageBucket: 'edspert19.appspot.com',
    iosBundleId: 'com.example.edproject.RunnerTests',
  );
}
